services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    container_name: api
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - mailpit
    networks:
      - to-do-list-nw
  postgres:
    image: postgres:16-bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - to-do-list-nw
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - to-do-list-nw
  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - to-do-list-nw
  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - to-do-list-nw
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - to-do-list-nw
  celery_worker:
    <<: *api
    command: /start-celeryworker
    container_name: celery_worker
  flower:
    <<: *api
    command: /start-flower
    ports:
      - "5557:5555"
    container_name: flower

networks:
  to-do-list-nw:
    external: true
volumes:
  postgres_data:
  static_volume:
  mailpit_data:
